[package]
name = "curvy"
version = "0.1.0"
edition = "2024"
default-run = "curvy"

[dependencies]
winit = "0.30.0"
softbuffer = "0.4.7"
image = "0.25.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
fontdue = "0.9"
